spring.application.name=patriotassist_gmu
frontend.url=http://localhost:3000
project.data.path=src/main/java/com/twentysixprojects/patriotassist/patriotassist_gmu/AllData
supported.terms=Summer 2025,Fall 2025
project.accountdata.path=src/main/java/com/twentysixprojects/patriotassist/patriotassist_gmu/Accounts/AccountData.json
jwt.secret=ArmanMeAndDrakeAreMakingAKillerWebAppGoodLuckToUs
jwt.expiration=3600000


spring.datasource.url=jdbc:postgresql://localhost:5432/grad_dev
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none