-- SQL Insert statements for GMU CS Requirements
-- Generated from the web scraper

-- Insert Degree Program
INSERT INTO degree_programs (name, total_credits, description) VALUES ('Computer Engineering BS', 120.0, 'Bachelor of Science in Computer Science') ON CONFLICT (name) DO UPDATE SET total_credits = 120.0;

-- Insert Categories
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Electrical and Computer Engineering', 1, 53.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 53.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Technical Electives', 1, 150.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 150.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Computer Science', 1, 10.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 10.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Mathematics and Statistics', 1, 24.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 24.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Physics', 1, 8.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 8.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Engineering', 1, 3.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 3.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('English, Communication, and Economics', 1, 9.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 9.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Computer Networks (CNWK)', 1, 21.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 21.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Embedded Systems (EMSY)', 1, 21.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 21.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Hardware and System Security (HSYS)', 1, 24.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 24.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Internet of Things (INOT)', 1, 24.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 24.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Robotics (ROB)', 1, 24.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 24.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Power and Energy Systems (PES)', 1, 24.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 24.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Space-Based Systems (SBSY)', 1, 24.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 24.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Semiconductor Engineering (SCEN)', 1, 15.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 15.0;

-- Insert Courses
INSERT INTO courses (code, title, credits) VALUES ('ECE 101', 'Introduction to Electrical and Computer Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Electrical and Computer Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 201', 'Introduction to Signals and Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Signals and Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 231', 'Digital System Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital System Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 232', 'Digital System Design Lab', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital System Design Lab', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 240', 'C Programming for Engineers', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'C Programming for Engineers', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 285', 'Electric Circuit Analysis I', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Electric Circuit Analysis I', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 286', 'Electric Circuit Analysis II', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Electric Circuit Analysis II', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 321', 'Continuous-Time Signals and Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Continuous-Time Signals and Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 333', 'Linear Electronics I (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Linear Electronics I (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 334', 'Linear Electronics Lab I', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Linear Electronics Lab I', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 340', 'Data Structures and Systems Programming in C', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Structures and Systems Programming in C', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 350', 'Embedded Systems and Hardware Interfaces', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Embedded Systems and Hardware Interfaces', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 391', 'Professional Development for Engineers', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Professional Development for Engineers', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 445', 'Computer Organization', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Organization', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 447', 'Microcontrollers', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Microcontrollers', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 448', 'FPGA Design with VHDL', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'FPGA Design with VHDL', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 465', 'Computer Networking Protocols', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Networking Protocols', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 492', 'Senior Advanced Design Project I (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Senior Advanced Design Project I (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 493', 'RS: Senior Advanced Design Project II (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'RS: Senior Advanced Design Project II (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 370', 'Introduction to Robotics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Robotics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 395', 'Electrical and Computer Engineering Internship', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Electrical and Computer Engineering Internship', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 409', 'Data Center Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Center Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 410', 'Applications of Discrete-Time Signal Processing', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Applications of Discrete-Time Signal Processing', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 411', 'Electricity Sector Engineering, Economics, and Regulation', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Electricity Sector Engineering, Economics, and Regulation', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 414', 'Grid Digitization and Automation', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Grid Digitization and Automation', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 415', 'Power System Analysis', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Power System Analysis', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 416', 'Electric Machinery and Modern Applications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Electric Machinery and Modern Applications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 417', 'Smart Grid and Cyber Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Smart Grid and Cyber Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 418', 'Power System Protection and Control', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Power System Protection and Control', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 419', 'Power Electronics for Modern Power Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Power Electronics for Modern Power Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 421', 'Classical Systems and Control Theory', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Classical Systems and Control Theory', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 424', 'Modern Control Systems Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Modern Control Systems Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 425', 'Secure RF Communications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Secure RF Communications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 427', 'Introduction to Machine Learning and Artificial Intelligence in Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Machine Learning and Artificial Intelligence in Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 430', 'Principles of Semiconductor Devices', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Principles of Semiconductor Devices', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 431', 'Digital Circuit Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Circuit Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 433', 'Linear Electronics II', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Linear Electronics II', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 446', 'Device Driver Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Device Driver Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 450', 'Mobile Robots', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Robots', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 455', 'GPU Architecture and Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'GPU Architecture and Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 460', 'Communication and Information Theory', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Communication and Information Theory', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 462', 'Data and Computer Communications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data and Computer Communications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 463', 'Digital Communications Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Communications Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 470', 'Introduction to Humanoid Robotics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Humanoid Robotics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 476', 'Cryptography Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cryptography Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 480', 'Small Spacecraft Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Small Spacecraft Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 488', 'Nanoelectronics Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Nanoelectronics Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 499', 'Special Topics in Electrical and Computer Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Special Topics in Electrical and Computer Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CYSE 462', 'Mobile Devices and Network Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Devices and Network Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 505', 'Hardware Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Hardware Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 508', 'Internet of Things', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Internet of Things', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 511', 'Computer Architecture', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Architecture', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 512', 'Computer Architecture Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Architecture Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 516', 'Mobile Systems and Applications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Systems and Applications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 521', 'Linear Systems and Control', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Linear Systems and Control', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 527', 'Learning From Data', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Learning From Data', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 528', 'Introduction to Random Processes in Electrical and Computer Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Random Processes in Electrical and Computer Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 530', 'Sensor Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Sensor Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 531', 'Introduction to Wireless Communications and Networks', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Wireless Communications and Networks', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 532', 'Secure Wireless Communications and Networks', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Secure Wireless Communications and Networks', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 535', 'Digital Signal Processing', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Signal Processing', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 537', 'Image Processing and Computer Vision', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Image Processing and Computer Vision', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 542', 'Computer Network Architectures and Protocols', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Network Architectures and Protocols', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 552', 'Big Data Technologies', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Big Data Technologies', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 554', 'Machine Learning for Embedded Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Machine Learning for Embedded Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 556', 'Neuromorphic Computing', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Neuromorphic Computing', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 567', 'Optical Fiber Communications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Optical Fiber Communications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 580', 'Small Spacecraft Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Small Spacecraft Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 590', 'Selected Topics in Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Selected Topics in Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 112', 'Introduction to Computer Programming (Mason Core)', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Computer Programming (Mason Core)', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 211', 'Object-Oriented Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Object-Oriented Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 471', 'Operating Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Operating Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 113', 'Analytic Geometry and Calculus I (Mason Core)', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Analytic Geometry and Calculus I (Mason Core)', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 114', 'Analytic Geometry and Calculus II', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Analytic Geometry and Calculus II', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 125', 'Discrete Mathematics I (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Discrete Mathematics I (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 203', 'Linear Algebra', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Linear Algebra', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 213', 'Analytic Geometry and Calculus III', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Analytic Geometry and Calculus III', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 214', 'Elementary Differential Equations', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Elementary Differential Equations', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('STAT 346', 'Probability for Engineers', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Probability for Engineers', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('PHYS 160', 'University Physics I (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'University Physics I (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('PHYS 161', 'University Physics I Laboratory (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'University Physics I Laboratory (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('PHYS 260', 'University Physics II (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'University Physics II (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('PHYS 261', 'University Physics II Laboratory (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'University Physics II Laboratory (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('ENGR 107', 'Introduction to Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ENGH 302', 'Advanced Composition (Mason Core) (Natural Sciences and Technology or Multidisciplinary section)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Advanced Composition (Mason Core) (Natural Sciences and Technology or Multidisciplinary section)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('COMM 100', 'Public Speaking (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Public Speaking (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECON 103', 'Contemporary Microeconomic Principles (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Contemporary Microeconomic Principles (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 465', 'Computer Networking Protocols', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Networking Protocols', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 460', 'Communication and Information Theory', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Communication and Information Theory', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 462', 'Data and Computer Communications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data and Computer Communications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 476', 'Cryptography Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cryptography Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 508', 'Internet of Things', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Internet of Things', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 532', 'Secure Wireless Communications and Networks', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Secure Wireless Communications and Networks', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('TCOM 535', 'The TCP/IP Suite of Internet Protocols', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'The TCP/IP Suite of Internet Protocols', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 447', 'Microcontrollers', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Microcontrollers', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 421', 'Classical Systems and Control Theory', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Classical Systems and Control Theory', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 446', 'Device Driver Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Device Driver Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 455', 'GPU Architecture and Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'GPU Architecture and Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 480', 'Small Spacecraft Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Small Spacecraft Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 516', 'Mobile Systems and Applications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Systems and Applications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 554', 'Machine Learning for Embedded Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Machine Learning for Embedded Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 465', 'Computer Networking Protocols', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Networking Protocols', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 505', 'Hardware Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Hardware Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 417', 'Smart Grid and Cyber Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Smart Grid and Cyber Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 455', 'GPU Architecture and Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'GPU Architecture and Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 462', 'Data and Computer Communications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data and Computer Communications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 476', 'Cryptography Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cryptography Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 512', 'Computer Architecture Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Architecture Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 532', 'Secure Wireless Communications and Networks', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Secure Wireless Communications and Networks', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 465', 'Computer Networking Protocols', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Networking Protocols', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 508', 'Internet of Things', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Internet of Things', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 414', 'Grid Digitization and Automation', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Grid Digitization and Automation', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 455', 'GPU Architecture and Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'GPU Architecture and Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 462', 'Data and Computer Communications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data and Computer Communications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 476', 'Cryptography Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cryptography Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 532', 'Secure Wireless Communications and Networks', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Secure Wireless Communications and Networks', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 554', 'Machine Learning for Embedded Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Machine Learning for Embedded Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 370', 'Introduction to Robotics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Robotics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 447', 'Microcontrollers', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Microcontrollers', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 421', 'Classical Systems and Control Theory', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Classical Systems and Control Theory', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 424', 'Modern Control Systems Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Modern Control Systems Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 450', 'Mobile Robots', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Robots', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 470', 'Introduction to Humanoid Robotics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Humanoid Robotics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 521', 'Linear Systems and Control', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Linear Systems and Control', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 530', 'Sensor Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Sensor Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 350', 'Embedded Systems and Hardware Interfaces', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Embedded Systems and Hardware Interfaces', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 415', 'Power System Analysis', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Power System Analysis', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 411', 'Electricity Sector Engineering, Economics, and Regulation', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Electricity Sector Engineering, Economics, and Regulation', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 414', 'Grid Digitization and Automation', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Grid Digitization and Automation', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 416', 'Electric Machinery and Modern Applications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Electric Machinery and Modern Applications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 417', 'Smart Grid and Cyber Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Smart Grid and Cyber Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 418', 'Power System Protection and Control', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Power System Protection and Control', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 419', 'Power Electronics for Modern Power Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Power Electronics for Modern Power Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 350', 'Embedded Systems and Hardware Interfaces', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Embedded Systems and Hardware Interfaces', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 480', 'Small Spacecraft Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Small Spacecraft Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 410', 'Applications of Discrete-Time Signal Processing', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Applications of Discrete-Time Signal Processing', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 427', 'Introduction to Machine Learning and Artificial Intelligence in Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Machine Learning and Artificial Intelligence in Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 460', 'Communication and Information Theory', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Communication and Information Theory', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 463', 'Digital Communications Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Communications Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ME 472', 'Spacecraft Subsystems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Spacecraft Subsystems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 550', 'System Engineering Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'System Engineering Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 333', 'Linear Electronics I (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Linear Electronics I (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 430', 'Principles of Semiconductor Devices', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Principles of Semiconductor Devices', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 431', 'Digital Circuit Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Circuit Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 488', 'Nanoelectronics Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Nanoelectronics Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 587', 'Design of Analog Integrated Circuits', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Design of Analog Integrated Circuits', credits = 3.0;

-- Insert Category Requirements
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 101')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 201')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 231')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 232')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 240')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 285')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 286')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 321')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 333')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 334')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 340')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 350')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 391')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 445')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 447')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 448')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 465')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 492')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'ECE 493')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 370')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 395')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 409')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 410')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 411')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 414')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 415')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 416')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 417')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 418')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 419')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 421')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 424')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 425')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 427')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 430')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 431')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 433')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 446')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 450')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 460')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 462')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 463')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 470')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 476')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 480')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 488')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 499')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CYSE 462')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 505')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 508')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 511')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 512')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 516')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 521')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 527')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 528')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 530')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 531')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 532')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 535')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 537')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 542')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 552')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 554')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 556')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 567')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 580')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'ECE 590')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'CS 112')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'CS 211')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'CS 471')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'MATH 113')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'MATH 114')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'MATH 125')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'MATH 203')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'MATH 213')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'MATH 214')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'STAT 346')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'PHYS 160')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'PHYS 161')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'PHYS 260')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'PHYS 261')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'ENGR 107')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'ENGH 302')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'COMM 100')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'ECON 103')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'ECE 465')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'ECE 460')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'ECE 462')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'ECE 476')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'ECE 508')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'ECE 532')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'TCOM 535')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'ECE 447')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'ECE 421')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'ECE 446')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'ECE 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'ECE 480')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'ECE 516')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'ECE 554')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'ECE 465')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'ECE 505')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'ECE 417')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'ECE 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'ECE 462')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'ECE 476')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'ECE 512')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'ECE 532')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 465')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 508')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 414')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 462')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 476')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 532')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 554')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 370')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 447')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 421')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 424')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 450')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 470')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 521')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 530')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'ECE 350')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'ECE 415')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'ECE 411')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'ECE 414')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'ECE 416')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'ECE 417')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'ECE 418')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'ECE 419')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'ECE 350')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'ECE 480')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'ECE 410')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'ECE 427')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'ECE 460')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'ECE 463')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'ME 472')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'ECE 550')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'ECE 333')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'ECE 430')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'ECE 431')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'ECE 488')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'ECE 587')) ON CONFLICT (category_id, course_id) DO NOTHING;

-- Insert Course Alternatives
