-- SQL Insert statements for GMU CS Requirements
-- Generated from the web scraper

-- Insert Degree Program
INSERT INTO degree_programs (name, total_credits, description) VALUES ('Computer Science BS', 120.0, 'Bachelor of Science in Computer Science') ON CONFLICT (name) DO UPDATE SET total_credits = 120.0;

-- Insert Categories
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Computer Science Core', 1, 35.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 35.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Senior Computer Science', 1, 78.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 78.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Mathematics', 1, 18.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 18.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Statistics', 1, 3.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 3.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Computer Science-Related Courses', 1, 57.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 57.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Approved Two-Course Sequences with Laboratories', 1, 17.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 17.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Additional Mason Core', 1, 9.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 9.0;

-- Insert Courses
INSERT INTO courses (code, title, credits) VALUES ('CS 110', 'Essentials of Computer Science 1', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Essentials of Computer Science 1', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 112', 'Introduction to Computer Programming (Mason Core)', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Computer Programming (Mason Core)', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 211', 'Object-Oriented Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Object-Oriented Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 262', 'Introduction to Low-Level Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Low-Level Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 306', 'Synthesis of Ethics and Law for the Computing Professional (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Synthesis of Ethics and Law for the Computing Professional (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 310', 'Data Structures', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Structures', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 321', 'Software Engineering (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Software Engineering (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 330', 'Formal Methods and Models', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Formal Methods and Models', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 367', 'Computer Systems and Programming', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Systems and Programming', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 471', 'Operating Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Operating Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 483', 'Analysis of Algorithms', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Analysis of Algorithms', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 455', 'Computer Communications and Networking', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Communications and Networking', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 468', 'Secure Programming and Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Secure Programming and Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 475', 'Concurrent and Distributed Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Concurrent and Distributed Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 487', 'Introduction to Cryptography', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Cryptography', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 425', 'Game Programming I', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Game Programming I', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 440', 'Compilers', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Compilers', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 450', 'Database Concepts', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Database Concepts', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 451', 'Computer Graphics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Graphics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 452', 'Virtual Reality', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Virtual Reality', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 455', 'Computer Communications and Networking', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Communications and Networking', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 463', 'Comparative Programming Languages', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Comparative Programming Languages', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 465', 'Computer Systems Architecture 1', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Systems Architecture 1', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 468', 'Secure Programming and Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Secure Programming and Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 469', 'Security Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Security Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 475', 'Concurrent and Distributed Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Concurrent and Distributed Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 477', 'Mobile Application Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Application Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 478', 'Natural Language Processing', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Natural Language Processing', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 480', 'Introduction to Artificial Intelligence', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Artificial Intelligence', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 482', 'Computer Vision', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Vision', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 484', 'Data Mining', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Mining', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 485', 'Autonomous Robotics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Autonomous Robotics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 487', 'Introduction to Cryptography', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Cryptography', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 490', 'Design Exhibition 2', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Design Exhibition 2', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 491', 'Industry-Sponsored Senior Design Project 2', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Industry-Sponsored Senior Design Project 2', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('CS 499', 'Special Topics in Computer Science 3', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Special Topics in Computer Science 3', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 446', 'Numerical Analysis I 4', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Numerical Analysis I 4', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 113', 'Analytic Geometry and Calculus I (Mason Core)', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Analytic Geometry and Calculus I (Mason Core)', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 114', 'Analytic Geometry and Calculus II', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Analytic Geometry and Calculus II', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 125', 'Discrete Mathematics I (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Discrete Mathematics I (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 203', 'Linear Algebra', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Linear Algebra', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 213', 'Analytic Geometry and Calculus III', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Analytic Geometry and Calculus III', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('STAT 344', 'Probability and Statistics for Engineers and Scientists I 1', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Probability and Statistics for Engineers and Scientists I 1', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('STAT 354', 'Probability and Statistics for Engineers and Scientists II', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Probability and Statistics for Engineers and Scientists II', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('OR 335', 'Discrete Systems Modeling and Simulation', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Discrete Systems Modeling and Simulation', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('OR 441', 'Deterministic Optimization', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Deterministic Optimization', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('OR 442', 'Stochastic Models', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Stochastic Models', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 301', 'Digital Electronics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Electronics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 350', 'Embedded Systems and Hardware Interfaces', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Embedded Systems and Hardware Interfaces', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 446', 'Device Driver Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Device Driver Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 447', 'Microcontrollers', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Microcontrollers', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 455', 'GPU Architecture and Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'GPU Architecture and Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 511', 'Computer Architecture', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Architecture', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('SWE 419', 'Object-Oriented Software Design and Implementation', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Object-Oriented Software Design and Implementation', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('SWE 432', 'Web Application Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Web Application Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('SWE 437', 'Software Testing and Maintenance', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Software Testing and Maintenance', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('SWE 443', 'Software Architectures', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Software Architectures', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('SYST 371', 'Systems Engineering Management', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Systems Engineering Management', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('SYST 470', 'Human Factors Engineering', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Human Factors Engineering', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('PHIL 371', 'Philosophy of the Natural Sciences', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Philosophy of the Natural Sciences', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('PHIL 376', 'Symbolic Logic', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Symbolic Logic', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ENGH 388', 'Professional and Technical Writing', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Professional and Technical Writing', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('BIOL 102', 'Introductory Biology I-Survey of Biodiversity and Ecology (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introductory Biology I-Survey of Biodiversity and Ecology (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('BIOL 106', 'Introductory Biology I Laboratory (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Introductory Biology I Laboratory (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('BIOL 107', 'Intro Biology II Lecture (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Intro Biology II Lecture (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('BIOL 103', 'Introductory Biology II-Survey of Cell and Molecular Biology (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introductory Biology II-Survey of Cell and Molecular Biology (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('BIOL 105', 'Introductory Biology II Laboratory (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Introductory Biology II Laboratory (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('CHEM 211& CHEM 213', 'General Chemistry I (Mason Core)and General Chemistry Laboratory I (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'General Chemistry I (Mason Core)and General Chemistry Laboratory I (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('CHEM 212& CHEM 214', 'General Chemistry II (Mason Core)and General Chemistry Laboratory II (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'General Chemistry II (Mason Core)and General Chemistry Laboratory II (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('GEOL 101& GEOL 103', 'Physical Geology (Mason Core)and Physical Geology Lab (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Physical Geology (Mason Core)and Physical Geology Lab (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('GEOL 102& GEOL 104', 'Historical Geology (Mason Core)and Historical Geology Laboratory (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Historical Geology (Mason Core)and Historical Geology Laboratory (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('PHYS 160& PHYS 161', 'University Physics I (Mason Core)and University Physics I Laboratory (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'University Physics I (Mason Core)and University Physics I Laboratory (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('PHYS 260& PHYS 261', 'University Physics II (Mason Core)and University Physics II Laboratory (Mason Core)', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'University Physics II (Mason Core)and University Physics II Laboratory (Mason Core)', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('COMM 100', 'Public Speaking (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Public Speaking (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ENGH 100', 'Composition for Multilingual Writers (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Composition for Multilingual Writers (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ENGH 302', 'Advanced Composition (Mason Core) (Natural Sciences section) 1', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Advanced Composition (Mason Core) (Natural Sciences section) 1', credits = 3.0;

-- Insert Category Requirements
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 110')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 112')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 211')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 262')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 306')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 310')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 321')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 330')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 367')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 471')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'CS 483')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 468')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 475')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 487')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 425')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 440')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 450')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 451')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 452')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 463')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 465')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 468')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 469')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 475')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 477')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 478')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 480')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 482')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 484')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 485')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 487')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 490')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 491')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'CS 499')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'MATH 446')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'MATH 113')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'MATH 114')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'MATH 125')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'MATH 203')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'MATH 213')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'STAT 344')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'STAT 354')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'OR 335')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'OR 441')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'OR 442')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'ECE 301')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'ECE 350')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'ECE 446')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'ECE 447')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'ECE 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'ECE 511')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'SWE 419')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'SWE 432')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'SWE 437')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'SWE 443')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'SYST 371')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'SYST 470')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'PHIL 371')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'PHIL 376')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'ENGH 388')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'BIOL 102')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'BIOL 106')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'BIOL 107')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'BIOL 103')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'BIOL 105')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'CHEM 211& CHEM 213')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'CHEM 212& CHEM 214')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'GEOL 101& GEOL 103')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'GEOL 102& GEOL 104')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'PHYS 160& PHYS 161')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'PHYS 260& PHYS 261')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'COMM 100')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'ENGH 100')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'ENGH 302')) ON CONFLICT (category_id, course_id) DO NOTHING;

-- Insert Course Alternatives
