-- SQL Insert statements for GMU CS Requirements
-- Generated from the web scraper

-- Insert Degree Program
INSERT INTO degree_programs (name, total_credits, description) VALUES ('Information Technology BS', 120.0, 'Bachelor of Science in Computer Science') ON CONFLICT (name) DO UPDATE SET total_credits = 120.0;

-- Insert Categories
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Foundation Courses', 1, 21.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 21.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Core Courses', 1, 33.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 33.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Two-Semester Sequence of Approved Capstone Design Courses', 1, 6.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 6.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration Gateway Courses', 1, 21.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 21.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Database Technology and Programming (DTP)', 1, 28.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 28.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Dual Concentration Requirements for Data Technology and Programming (DTP)', 1, 28.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 28.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Health Information Technology (HIT)', 1, 13.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 13.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Dual Concentration Requirements for Health Information Technology (HIT)', 1, 13.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 13.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Cyber Security (CYBR)', 1, 30.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 30.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Dual Concentration Requirements for Cyber Security (CYBR)', 1, 30.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 30.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Network and Telecommunications (NTEL)', 1, 21.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 21.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Dual Concentration Requirements for Network and Telecommunications (NTEL)', 1, 21.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 21.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Web Application Development (WADV)', 1, 22.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 22.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Dual Concentration Requirements for Web Application Development (WADV)', 1, 22.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 22.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Concentration in Cloud Computing (CCG)', 1, 15.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 15.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Dual Concentration Requirements for Cloud Computing (CCG)', 1, 15.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 15.0;
INSERT INTO requirement_categories (name, degree_id, total_credits) VALUES ('Other Major Requirements', 1, 16.0) ON CONFLICT (name, degree_id) DO UPDATE SET total_credits = 16.0;

-- Insert Courses
INSERT INTO courses (code, title, credits) VALUES ('IT 102', 'Discrete Structures', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Discrete Structures', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 104', 'Introduction to Computing (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Computing (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 105', 'IT Architecture Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'IT Architecture Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 106', 'Introduction to IT Problem Solving Using Computer Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to IT Problem Solving Using Computer Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 206', 'Object Oriented Techniques for IT Problem Solving', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Object Oriented Techniques for IT Problem Solving', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 216', 'Systems Analysis and Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Systems Analysis and Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('STAT 250', 'Introductory Statistics I (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introductory Statistics I (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 207', 'Applied IT Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Applied IT Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 213', 'Multimedia and Web Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Multimedia and Web Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 214', 'Database Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Database Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 223', 'Information Security Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Information Security Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 300', 'Modern Telecommunications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Modern Telecommunications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 304', 'IT in the Global Economy', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'IT in the Global Economy', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 341', 'Data Communications and Network Principles', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Communications and Network Principles', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 342', 'Operating Systems Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Operating Systems Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 343', 'IT Project Management (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'IT Project Management (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MBUS 300', 'Accounting in a Global Economy', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Accounting in a Global Economy', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('SYST 469', 'Human Computer Interaction', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Human Computer Interaction', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 492', 'Senior Design Project I (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Senior Design Project I (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 493', 'Senior Design Project II (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Senior Design Project II (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 206', 'Object Oriented Techniques for IT Problem Solving', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Object Oriented Techniques for IT Problem Solving', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 214', 'Database Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Database Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 214', 'Database Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Database Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 223', 'Information Security Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Information Security Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 341', 'Data Communications and Network Principles', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Communications and Network Principles', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 213', 'Multimedia and Web Design', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Multimedia and Web Design', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 341', 'Data Communications and Network Principles', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Communications and Network Principles', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 306', 'Data Structures and Algorithms in Java', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Structures and Algorithms in Java', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 314', 'Database Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Database Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 315', 'Mobile Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 322', 'Health Data Challenges', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Health Data Challenges', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 369', 'Cyber Security of Data and Software', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cyber Security of Data and Software', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 390', 'Rapid Development of Scalable Cloud Applications', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Rapid Development of Scalable Cloud Applications', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 409', 'Python Web Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Python Web Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 410', 'Web Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Web Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 414', 'Database Administration', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Database Administration', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 416', 'Machine Learning for Information Sciences', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Machine Learning for Information Sciences', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 306', 'Data Structures and Algorithms in Java', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Data Structures and Algorithms in Java', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 314', 'Database Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Database Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 315', 'Mobile Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 322', 'Health Data Challenges', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Health Data Challenges', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 369', 'Cyber Security of Data and Software', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cyber Security of Data and Software', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 390', 'Rapid Development of Scalable Cloud Applications', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Rapid Development of Scalable Cloud Applications', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 409', 'Python Web Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Python Web Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 410', 'Web Programming', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Web Programming', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 414', 'Database Administration', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Database Administration', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 416', 'Machine Learning for Information Sciences', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Machine Learning for Information Sciences', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('HAP 360', 'Introduction to Health Information Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Health Information Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 322', 'Health Data Challenges', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Health Data Challenges', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 324', 'Health Information Technology Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Health Information Technology Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 390', 'Rapid Development of Scalable Cloud Applications', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Rapid Development of Scalable Cloud Applications', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('STAT 362', 'Introduction to Computer Statistical Packages', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Computer Statistical Packages', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('HAP 360', 'Introduction to Health Information Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Health Information Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 322', 'Health Data Challenges', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Health Data Challenges', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 324', 'Health Information Technology Fundamentals', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Health Information Technology Fundamentals', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 390', 'Rapid Development of Scalable Cloud Applications', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Rapid Development of Scalable Cloud Applications', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('STAT 362', 'Introduction to Computer Statistical Packages', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introduction to Computer Statistical Packages', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 352', 'Security Administration of Linux Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Security Administration of Linux Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 353', 'Information Defense Technologies', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Information Defense Technologies', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 357', 'Computer Crime, Forensics, and Auditing', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Crime, Forensics, and Auditing', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 366', 'Network Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Network Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 369', 'Cyber Security of Data and Software', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cyber Security of Data and Software', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 425', 'Election Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Election Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 429', 'Security Accreditation of Information Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Security Accreditation of Information Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 462', 'Applied Cyber Threat Analysis', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Applied Cyber Threat Analysis', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 466', 'Foundations of Cryptography and Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Foundations of Cryptography and Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 467', 'Network Defense', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Network Defense', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 352', 'Security Administration of Linux Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Security Administration of Linux Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 353', 'Information Defense Technologies', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Information Defense Technologies', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 357', 'Computer Crime, Forensics, and Auditing', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Computer Crime, Forensics, and Auditing', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 366', 'Network Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Network Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 369', 'Cyber Security of Data and Software', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cyber Security of Data and Software', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 425', 'Election Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Election Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 429', 'Security Accreditation of Information Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Security Accreditation of Information Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 462', 'Applied Cyber Threat Analysis', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Applied Cyber Threat Analysis', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 466', 'Foundations of Cryptography and Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Foundations of Cryptography and Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 467', 'Network Defense', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Network Defense', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 301', 'Digital Electronics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Electronics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 366', 'Network Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Network Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 442', 'Cloud Infrastructure', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cloud Infrastructure', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 445', 'Advanced Networking Principles', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Advanced Networking Principles', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 455', 'Wireless Communications and Networking', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Wireless Communications and Networking', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 484', 'Voice Communications Technologies', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Voice Communications Technologies', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 488', 'Fundamentals of Satellite Communications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Fundamentals of Satellite Communications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('ECE 301', 'Digital Electronics', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Electronics', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 366', 'Network Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Network Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 442', 'Cloud Infrastructure', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cloud Infrastructure', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 445', 'Advanced Networking Principles', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Advanced Networking Principles', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 455', 'Wireless Communications and Networking', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Wireless Communications and Networking', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 484', 'Voice Communications Technologies', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Voice Communications Technologies', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 488', 'Fundamentals of Satellite Communications', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Fundamentals of Satellite Communications', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 315', 'Mobile Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 331', 'Front-End Web Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Front-End Web Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 332', 'Web Server Administration', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Web Server Administration', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 335', 'Web Development using Content Management Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Web Development using Content Management Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 390', 'Rapid Development of Scalable Cloud Applications', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Rapid Development of Scalable Cloud Applications', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 415', 'Information Visualization', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Information Visualization', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 431', 'Advanced Web Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Advanced Web Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 479', 'Digital Media and Web Design Capstone', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Media and Web Design Capstone', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 315', 'Mobile Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Mobile Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 331', 'Front-End Web Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Front-End Web Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 332', 'Web Server Administration', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Web Server Administration', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 335', 'Web Development using Content Management Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Web Development using Content Management Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 390', 'Rapid Development of Scalable Cloud Applications', 1.0) ON CONFLICT (code) DO UPDATE SET title = 'Rapid Development of Scalable Cloud Applications', credits = 1.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 415', 'Information Visualization', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Information Visualization', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 431', 'Advanced Web Development', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Advanced Web Development', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 479', 'Digital Media and Web Design Capstone', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Digital Media and Web Design Capstone', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 442', 'Cloud Infrastructure', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cloud Infrastructure', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 451', 'Cloud Services Management', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cloud Services Management', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 461', 'Application Development in Cloud', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Application Development in Cloud', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 471', 'Big Data on Cloud Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Big Data on Cloud Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 481', 'Cloud Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cloud Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 442', 'Cloud Infrastructure', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cloud Infrastructure', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 451', 'Cloud Services Management', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cloud Services Management', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 461', 'Application Development in Cloud', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Application Development in Cloud', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 471', 'Big Data on Cloud Systems', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Big Data on Cloud Systems', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 481', 'Cloud Security', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Cloud Security', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('COMM 100', 'Public Speaking (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Public Speaking (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('IT 293', 'Applied IT: Junior Transition', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Applied IT: Junior Transition', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 108', 'Introductory Calculus with Business Applications (Mason Core)', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Introductory Calculus with Business Applications (Mason Core)', credits = 3.0;
INSERT INTO courses (code, title, credits) VALUES ('MATH 113', 'Analytic Geometry and Calculus I (Mason Core)', 4.0) ON CONFLICT (code) DO UPDATE SET title = 'Analytic Geometry and Calculus I (Mason Core)', credits = 4.0;
INSERT INTO courses (code, title, credits) VALUES ('HNRT 225', 'Applied Calculus', 3.0) ON CONFLICT (code) DO UPDATE SET title = 'Applied Calculus', credits = 3.0;

-- Insert Category Requirements
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'IT 102')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'IT 104')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'IT 105')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'IT 106')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'IT 206')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'IT 216')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (1, (SELECT id FROM courses WHERE code = 'STAT 250')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 207')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 213')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 214')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 223')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 300')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 304')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 341')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 342')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'IT 343')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'MBUS 300')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (2, (SELECT id FROM courses WHERE code = 'SYST 469')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'IT 492')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (3, (SELECT id FROM courses WHERE code = 'IT 493')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'IT 206')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'IT 214')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'IT 214')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'IT 223')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'IT 341')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'IT 213')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (4, (SELECT id FROM courses WHERE code = 'IT 341')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 306')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 314')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 315')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 322')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 369')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 390')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 409')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 410')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 414')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (5, (SELECT id FROM courses WHERE code = 'IT 416')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 306')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 314')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 315')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 322')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 369')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 390')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 409')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 410')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 414')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (6, (SELECT id FROM courses WHERE code = 'IT 416')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'HAP 360')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'IT 322')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'IT 324')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'IT 390')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (7, (SELECT id FROM courses WHERE code = 'STAT 362')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'HAP 360')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'IT 322')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'IT 324')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'IT 390')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (8, (SELECT id FROM courses WHERE code = 'STAT 362')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 352')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 353')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 357')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 366')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 369')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 425')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 429')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 462')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 466')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (9, (SELECT id FROM courses WHERE code = 'IT 467')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 352')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 353')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 357')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 366')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 369')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 425')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 429')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 462')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 466')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (10, (SELECT id FROM courses WHERE code = 'IT 467')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'ECE 301')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'IT 366')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'IT 442')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'IT 445')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'IT 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'IT 484')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (11, (SELECT id FROM courses WHERE code = 'IT 488')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'ECE 301')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'IT 366')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'IT 442')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'IT 445')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'IT 455')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'IT 484')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (12, (SELECT id FROM courses WHERE code = 'IT 488')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'IT 315')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'IT 331')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'IT 332')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'IT 335')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'IT 390')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'IT 415')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'IT 431')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (13, (SELECT id FROM courses WHERE code = 'IT 479')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'IT 315')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'IT 331')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'IT 332')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'IT 335')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'IT 390')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'IT 415')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'IT 431')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (14, (SELECT id FROM courses WHERE code = 'IT 479')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'IT 442')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'IT 451')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'IT 461')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'IT 471')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (15, (SELECT id FROM courses WHERE code = 'IT 481')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (16, (SELECT id FROM courses WHERE code = 'IT 442')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (16, (SELECT id FROM courses WHERE code = 'IT 451')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (16, (SELECT id FROM courses WHERE code = 'IT 461')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (16, (SELECT id FROM courses WHERE code = 'IT 471')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (16, (SELECT id FROM courses WHERE code = 'IT 481')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (17, (SELECT id FROM courses WHERE code = 'COMM 100')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (17, (SELECT id FROM courses WHERE code = 'IT 293')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (17, (SELECT id FROM courses WHERE code = 'MATH 108')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (17, (SELECT id FROM courses WHERE code = 'MATH 113')) ON CONFLICT (category_id, course_id) DO NOTHING;
INSERT INTO category_requirements (category_id, course_id) VALUES (17, (SELECT id FROM courses WHERE code = 'HNRT 225')) ON CONFLICT (category_id, course_id) DO NOTHING;

-- Insert Course Alternatives
